### ISSUE TITLE
release

### ISSUE THREAD

**Issue by ghost** [XFZAIMFQ/Actions-OpenWrt-N1#1]
请教一个问题，编译好了，release发布需要哪几个参数？

**Comment by XFZAIMFQ** [comment]
只需要一个github的TOKEN就行

**Comment by ghost** [comment]
为什么我加了还是不行，提示缺少参数

**Comment by XFZAIMFQ** [comment]
在项目库的设置 Repository secrets 中添加你的github的TOKEN,然后命名为release发布这个步骤中的TOKEN名称

**Comment by ghost** [comment]
(token: ${{ secrets.ACCESS_TOKEN }})这里的ACCESS要和Repository secrets 中添加的github的TOKEN一样对吗？

**Comment by XFZAIMFQ** [comment]
对,将 Repository secrets 中添加的github的TOKEN命名为(token: ${{ secrets.ACCESS_TOKEN }})中的ACCESS_TOKEN

**Comment by ghost** [comment]
好的，明白了，怪不得我试了几个仓库都是这个问题，原因是命名的不一样，谢谢了
